create table if not exists public.onboarding_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique,
  step varchar not null default 'chat' check (step in ('chat','details','booking','done')),
  status varchar not null default 'in_progress',
  stress_mode varchar not null default 'neutral' check (stress_mode in ('neutral','elevated')),
  calm_mode_opt_in boolean not null default false,
  assessment jsonb not null default '{}'::jsonb,
  created_at timestamp(6) without time zone not null default now(),
  updated_at timestamp(6) without time zone not null default now()
);

create table if not exists public.document_details (
  id bigint generated by default as identity primary key,
  onboarding_session_id bigint not null unique references public.onboarding_sessions(id),
  full_name varchar,
  date_of_birth date,
  address text,
  field_sources jsonb not null default '{}'::jsonb,
  confirmed_at timestamp(6) without time zone,
  created_at timestamp(6) without time zone not null default now(),
  updated_at timestamp(6) without time zone not null default now()
);

create table if not exists public.consent_events (
  id bigint generated by default as identity primary key,
  onboarding_session_id bigint not null references public.onboarding_sessions(id),
  event_type varchar not null check (event_type in ('granted','revoked')),
  policy_version varchar not null default '2026-08-20',
  created_at timestamp(6) without time zone not null default now(),
  updated_at timestamp(6) without time zone not null default now()
);
create index if not exists index_consent_events_on_onboarding_session_id on public.consent_events(onboarding_session_id);

create table if not exists public.appointment_slots (
  id bigint generated by default as identity primary key,
  starts_at timestamp(6) without time zone not null unique,
  channel varchar not null default 'video_or_phone',
  created_at timestamp(6) without time zone not null default now(),
  updated_at timestamp(6) without time zone not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  onboarding_session_id bigint not null unique references public.onboarding_sessions(id),
  appointment_slot_id bigint not null unique references public.appointment_slots(id),
  reference varchar not null unique,
  created_at timestamp(6) without time zone not null default now(),
  updated_at timestamp(6) without time zone not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  anonymous_session_id uuid not null,
  event_name varchar not null,
  step varchar,
  duration_ms integer,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamp(6) without time zone not null default now(),
  updated_at timestamp(6) without time zone not null default now()
);
create index if not exists index_analytics_events_on_event_name_and_created_at on public.analytics_events(event_name, created_at);

create table if not exists public.deletion_audits (
  id bigint generated by default as identity primary key,
  subject_digest varchar not null,
  scope varchar not null default 'all_onboarding_data',
  created_at timestamp(6) without time zone not null default now(),
  updated_at timestamp(6) without time zone not null default now()
);
create index if not exists index_deletion_audits_on_subject_digest on public.deletion_audits(subject_digest);

alter table public.onboarding_sessions enable row level security;
alter table public.document_details enable row level security;
alter table public.consent_events enable row level security;
alter table public.appointment_slots enable row level security;
alter table public.bookings enable row level security;
alter table public.analytics_events enable row level security;
alter table public.deletion_audits enable row level security;

revoke all on table public.onboarding_sessions, public.document_details, public.consent_events,
  public.appointment_slots, public.bookings, public.analytics_events, public.deletion_audits from anon, authenticated;

create table if not exists public.schema_migrations (version varchar primary key);
insert into public.schema_migrations(version) values ('20260820000001') on conflict do nothing;

insert into public.appointment_slots(starts_at)
values
  ('2026-08-20 14:00:00'), ('2026-08-20 16:30:00'), ('2026-08-20 19:00:00'),
  ('2026-08-21 15:00:00'), ('2026-08-21 18:30:00'), ('2026-08-21 21:15:00'),
  ('2026-08-24 14:30:00'), ('2026-08-24 17:00:00'), ('2026-08-24 20:00:00')
on conflict do nothing;

insert into public.onboarding_sessions(user_id, step, status)
select
  ('00000000-0000-4000-8000-' || lpad(series::text, 12, '0'))::uuid,
  case when series <= 18 then 'chat' when series <= 40 then 'details' when series <= 68 then 'booking' else 'done' end,
  case when series > 68 then 'completed' else 'in_progress' end
from generate_series(1, 120) as series
on conflict (user_id) do nothing;

insert into public.analytics_events(anonymous_session_id, event_name, step, duration_ms)
select user_id, 'session_started', 'chat', 0 from public.onboarding_sessions
where user_id::text like '00000000-0000-4000-8000-%'
on conflict do nothing;

insert into public.bookings(onboarding_session_id, appointment_slot_id, reference)
select session.id, slot.id, seed.reference
from (values
  ('00000000-0000-4000-8000-000000000069'::uuid, '2026-08-20 14:00:00'::timestamp, 'HB-4271'),
  ('00000000-0000-4000-8000-000000000070'::uuid, '2026-08-21 18:30:00'::timestamp, 'HB-6184')
) as seed(user_id, starts_at, reference)
join public.onboarding_sessions session on session.user_id = seed.user_id
join public.appointment_slots slot on slot.starts_at = seed.starts_at
on conflict do nothing;
