-- Permit public anonymous onboarding while keeping permanent staff identities
-- pre-provisioned. Existing staff sign-ins do not invoke this creation hook.
create or replace function public.hook_restrict_staff_signup(event jsonb)
returns jsonb
language plpgsql
set search_path = ''
as $$
begin
  if coalesce((event->'user'->>'is_anonymous')::boolean, false) then
    return '{}'::jsonb;
  end if;

  return jsonb_build_object(
    'error', jsonb_build_object(
      'http_code', 403,
      'message', 'Staff accounts are provisioned by an administrator.'
    )
  );
end;
$$;

grant usage on schema public to supabase_auth_admin;
grant execute on function public.hook_restrict_staff_signup(jsonb) to supabase_auth_admin;
revoke execute on function public.hook_restrict_staff_signup(jsonb) from anon, authenticated, public;

create table if not exists public.admin_access_audits (
  id bigint generated by default as identity primary key,
  actor_digest varchar not null,
  action varchar not null check (action in ('analytics_viewed', 'analytics_denied')),
  created_at timestamp(6) without time zone not null default now(),
  updated_at timestamp(6) without time zone not null default now()
);
create index if not exists index_admin_access_audits_on_actor_digest
  on public.admin_access_audits(actor_digest);
create index if not exists index_admin_access_audits_on_action_and_created_at
  on public.admin_access_audits(action, created_at);

alter table public.admin_access_audits enable row level security;
revoke all on table public.admin_access_audits from anon, authenticated;

insert into public.schema_migrations(version)
values ('20260820000002')
on conflict do nothing;
