FROM ruby:3.4.7-bookworm

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y imagemagick libpq-dev postgresql-client tesseract-ocr && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .

EXPOSE 3001
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-p", "3001"]
